Repository sprint-team5/dallaem, pull requests merged in 2024-08, with the labels that each got.

#75 #74 마이페이지 info 컴포넌트 data fetching 관련 동작 추가
  src/actions/fetchMyPageInfo.ts
  src/app/(myPage)/mypage/page.tsx
  src/components/pages/mypage/MyPageInfoTap.tsx
  src/components/pages/mypage/MyPageInfoWrapper.tsx
  src/components/public/Card/Card.tsx
Labels: enhancement, feat

#78 feat : Card 컴포넌트 props 추가
  src/components/public/Card/Card.test.tsx
  src/components/public/Card/Card.tsx
  src/components/public/Card/CardCancel.tsx
  src/components/public/Card/CardReview.tsx
Labels: refactoring, feat

#82 #80 로그인, 회원가입 페이지 test 코드 작성 완료
  jest.config.js
  src/actions/api-actions/Auths.ts
  src/app/auth/@signin/SigninForm.test.tsx
  src/app/auth/@signin/SigninForm.tsx
  src/app/auth/@signup/SignupForm.test.tsx
  src/app/auth/@signup/SignupForm.tsx
Labels: feat

#83 feat : Add Middleware
  src/middleware.ts
Labels: feat

#87 #39 찜한 모임 페이지 테스트 코드 작성 및 버그 수정
  src/app/wishlist/wishlist.test.tsx
  src/components/pages/wishlist/List.tsx
  src/hooks/useWishList.tsx
Labels: feat, fix

#88 #79 리뷰 생성 모달 구현 및 모달 api 연동
  next.config.mjs
  src/actions/addReview.ts
  src/actions/apis/Auths.ts
  src/actions/editProfileInfo.ts
  src/actions/fetchMyPageInfo.ts
  src/actions/generateMeetUp.ts
  src/actions/getUserInfo.ts
  src/actions/onLogout.ts
  src/app/(myPage)/mypage/@addReview/(.)addReview/page.tsx
  src/app/(myPage)/mypage/@addReview/default.tsx
  src/app/(myPage)/mypage/layout.tsx
  src/components/pages/mypage/MyPageInfoTap.tsx
  src/components/pages/mypage/MyPageInfoTapButton.tsx
  src/components/pages/mypage/MyPageInfoWrapper.tsx
  src/components/public/Review/ReviewHeartBtn/ReviewHeartBtn.tsx
  src/components/public/modal/ReviewModal.tsx
Labels: feat

#93 feat : prviate public 라우터 alert창
  public/icon/staticIcon/error.svg
  src/app/layout.tsx
  src/components/public/Toast.tsx
  src/middleware.ts
  src/provider/ToastProvider.tsx
Labels: feat

#97 #92 백엔드 api 변경 및 유저 기능 완성에 따른 관련 코드 수정
  src/actions/addReview.ts
  src/actions/fetchMyPageInfo.ts
  src/actions/getUserInfo.ts
  src/actions/onLogout.ts
  src/actions/setCookies.ts
  src/app/(myPage)/mypage/layout.tsx
  src/app/(myPage)/mypage/page.tsx
  src/components/pages/mypage/MyPageInfoTap.tsx
  src/components/pages/mypage/MyPageInfoWrapper.tsx
  src/components/public/ProfileBox.tsx
Labels: enhancement, fix

#98 #96 에러 수정 및 디테일 수정
  __test__/page.test.jsx
  src/actions/api-actions/Auths.ts
  src/actions/api-hooks/Auths.ts
  src/actions/getUserDataFn.ts
  src/actions/postSigninFn.ts
  src/actions/postSignupFn.ts
  src/app/auth/@signin/page.tsx
  src/app/auth/@signup/page.tsx
  src/components/pages/auth/@signin/SigninForm.test.tsx
  src/components/pages/auth/@signin/SigninForm.tsx
  src/components/pages/auth/@signin/Validations.ts
  src/components/pages/auth/@signup/SignupForm.test.tsx
  src/components/pages/auth/@signup/SignupForm.tsx
  src/components/pages/auth/@signup/Validations.ts
  src/components/pages/mainpage/HeadContent.tsx
  src/components/public/gnb/GNB.tsx
  src/components/public/gnb/components/ProfileComponent.tsx
  src/hooks/useGetUserData.ts
  src/hooks/usePostSignin.tsx
  src/hooks/usePostSignup.ts
Labels: refactoring, fix

#100 feat : 나의 모임, 모임 찾기, 리뷰 스켈레톤
  src/components/pages/allReview/List.tsx
  src/components/public/Skeleton/CardSkeleton.tsx
  src/components/public/Skeleton/MeetingCardSkeleton.tsx
  src/components/public/Skeleton/ReviewSkeleton.tsx
  src/constants/skeleton.ts
Labels: feat

#102 #101 메인 페이지에 리뷰 미리보기 추가
  __test__/page.test.jsx
  src/actions/allReviewActions.ts
  src/app/page.tsx
  src/components/pages/mainpage/HeadContent.test.tsx
  src/components/pages/mainpage/HeadContent.tsx
  src/components/pages/mainpage/ReviewPreview.test.tsx
  src/components/pages/mainpage/ReviewPreview.tsx
  src/components/public/button/Button.tsx
Labels: feat

#103 #99 리뷰 조회 컴포넌트 refactoring
  src/actions/editProfileInfo.ts
  src/actions/fetchMyPageInfo.ts
  src/app/(myPage)/mypage/@addReview/(.)addReview/page.tsx
  src/app/(myPage)/mypage/@edit/(.)edit/page.tsx
  src/app/(myPage)/mypage/layout.tsx
  src/app/layout.tsx
  src/components/app/provider.tsx
  src/components/pages/mypage/MyPageInfoTap.tsx
  src/components/pages/mypage/MyPageInfoWrapper.tsx
  src/components/pages/mypage/ReviewStateButton.tsx
  src/components/public/Card/Card.tsx
  src/components/public/Card/CardReview.tsx
  src/components/public/ProfileBox.tsx
  src/components/public/modal/ProfileEditModal.tsx
  src/components/public/modal/ReviewModal.tsx
  tailwind.config.ts
Labels: feat, fix

#104 #73 모임 만들기 등
  src/actions/api-hooks/getParticipants.ts
  src/actions/cancelMeeting.ts
  src/actions/checkLogin.ts
  src/actions/generateMeetUp.ts
  src/actions/getUserInfo.ts
  src/actions/joinMeeting.ts
  src/actions/quitMeeting.ts
  src/app/findMeeting/page.tsx
  src/app/wishlist/wishlist.test.tsx
  src/components/pages/findMeeting/CreateMeeting/CreateMeetingModal.tsx
  src/components/pages/findMeeting/CreateMeeting/styles.scss
  src/components/pages/findMeeting/MeetingCard/MeetingDetail/BottomBanner.tsx
  src/components/pages/findMeeting/MeetingCard/MeetingDetail/MeetingDetail.tsx
  src/components/pages/findMeeting/MeetingCard/MeetingList/MeetingList.tsx
  src/components/public/Calendars/Calendars.tsx
  src/components/public/CloseBtn.tsx
  src/components/public/Review/Review.tsx
  src/hooks/useMeetingDetail.tsx
  src/util/cookies.ts
  src/util/modal.ts
Labels: feat, fix

#108 feat : replace 추가
  src/components/public/Toast.tsx
Labels: bug, feat

#109 #106 잘못된 코드 수정 및 에러 처리 로직과 로딩 처리 추가
  src/app/layout.tsx
  src/components/pages/auth/@signin/SigninForm.tsx
  src/components/pages/auth/@signup/SignupForm.tsx
  src/components/pages/mainpage/HeadContent.tsx
  src/components/pages/mainpage/ReviewPreview.tsx
  src/components/public/button/Button.tsx
  src/components/public/gnb/GNB.tsx
  src/components/public/gnb/components/ProfileComponent.test.tsx
  src/components/public/gnb/components/ProfileComponent.tsx
  src/components/public/input/InputField.tsx
Labels: refactoring, fix

#110 #107 마이페이지 무한 스크롤 구현
  src/actions/fetchMyPageInfo.ts
  src/app/(myPage)/mypage/layout.tsx
  src/app/(myPage)/mypage/page.tsx
  src/components/pages/mypage/MyPageInfoTap.tsx
  src/components/pages/mypage/MyPageInfoWrapper.tsx
  src/components/public/ProfileBox.tsx
Labels: feat, fix

#112 모임 찾기 리스트 무한스크롤 구현
  src/app/findMeeting/page.tsx
  src/components/pages/findMeeting/MeetingCard/MeetingDetail/BottomBanner.tsx
  src/components/pages/findMeeting/MeetingCard/MeetingDetail/MeetingDetail.tsx
  src/components/pages/findMeeting/MeetingCard/MeetingList/MeetingList.tsx
  src/hooks/useMeetingDetail.tsx
  src/types/meeting/meeting.ts
Labels: feat

#114 fix: 모임 상세 refetch 오류 수정
  src/app/findMeeting/[slug]/page.tsx
  src/components/pages/findMeeting/MeetingCard/MeetingDetail/BottomBanner.tsx
Labels: bug

#117 #115 만료모임 스타일 적용 + refetch 이슈로 cache no-store 적용
  src/actions/api-hooks/getMeetingDetail.ts
  src/app/findMeeting/[slug]/page.tsx
  src/components/pages/findMeeting/MeetingCard/MeetingDetail/BottomBanner.tsx
  src/components/pages/findMeeting/MeetingCard/MeetingList/MeetingList.tsx
Labels: bug, feat

#120 #118 디자인 디테일 수정
  src/components/pages/findMeeting/FilterCalendar/FilterCalendar.tsx
  src/components/pages/findMeeting/FilterSort/FilterSort.tsx
  src/components/public/Filter/Filter.tsx
  src/components/public/gnb/components/ProfileComponent.tsx
Labels: refactoring

#122 #119 통합 테스트시 발견한 버그 수정
  src/app/(myPage)/mypage/@edit/(.)edit/page.tsx
  src/components/pages/findMeeting/FilterCalendar/FilterCalendar.tsx
  src/components/pages/findMeeting/FilterSort/FilterSort.tsx
  src/components/pages/mypage/MyPageInfoTapButton.tsx
  src/components/pages/mypage/MyPageInfoWrapper.tsx
  src/components/pages/mypage/ReviewStateButton.tsx
  src/components/public/Filter/Filter.tsx
  src/components/public/modal/ProfileEditModal.tsx
  src/components/public/modal/ReviewModal.tsx
Labels: fix

#123 refactor : 찜모임 use wish list 리팩토링
  src/components/pages/allReview/List.tsx
  src/components/pages/wishlist/ByeBtn.tsx
  src/components/pages/wishlist/List.tsx
  src/hooks/useWishList.tsx
Labels: refactoring, feat

#124 #121 refactor createmeetingmodal 컴포넌트 리팩토링
  src/app/findMeeting/page.tsx
  src/components/pages/findMeeting/CreateMeeting/CreateMeetingForm.tsx
  src/components/pages/findMeeting/CreateMeeting/CreateMeetingModal.tsx
  src/components/pages/findMeeting/CreateMeeting/selectComponents/SelectServiceButton.tsx
  src/components/pages/findMeeting/CreateMeeting/selectComponents/SelectServiceRadioGroup.tsx
  src/components/pages/findMeeting/CreateMeeting/selectComponents/SelectTimeButton.tsx
  src/components/public/input/InputField.tsx
  src/components/public/input/components/Dropdown.test.tsx
  src/components/public/input/components/Dropdown.tsx
Labels: refactoring, fix

#126 #125 createmeetingform 알림 연동 및 리팩토링
  src/actions/apis/Auths.ts
  src/actions/generateMeetUp.ts
  src/actions/getMeetingList.ts
  src/actions/joinGathering.ts
  src/app/findMeeting/page.tsx
  src/components/pages/auth/@signup/SignupForm.tsx
  src/components/pages/findMeeting/CreateMeeting/CreateMeetingForm.tsx
  src/components/pages/findMeeting/MeetingCard/MeetingDetail/BottomBanner.tsx
  src/components/pages/findMeeting/MeetingCard/MeetingList/MeetingList.tsx
  src/components/public/modal/CompleteSignUpModal.tsx
  src/components/public/modal/CreateMeetingModal.tsx
  src/components/public/modal/GenerateMeetUpModal.tsx
  src/components/public/modal/styles.scss
  src/hooks/Gatherings/useCreateGathering.tsx
  src/hooks/Gatherings/useJoinGathering.tsx
  src/hooks/useGetMeetingList.tsx
Labels: refactoring, feat, fix

#130 #129 마이페이지 업데이트 버그 수정 및 UI 업데이트
  src/components/pages/findMeeting/MeetingCard/MeetingDetail/BottomBanner.tsx
  src/components/pages/mypage/MyPageDefault.tsx
  src/components/pages/mypage/MyPageInfoWrapper.tsx
Labels: feat, fix

#135 #134 레이아웃 버그 수정
  src/app/(myPage)/mypage/layout.tsx
  src/app/layout.tsx
  src/components/pages/mypage/MyPageInfoTapButton.tsx
  src/components/pages/mypage/MyPageInfoWrapper.tsx
  src/components/pages/mypage/ReviewStateButton.tsx
  src/components/pages/wishlist/ByeBtn.tsx
  src/components/pages/wishlist/List.tsx
  src/components/pages/wishlist/WishBtn.tsx
  src/components/public/ProfileBox.tsx
  src/components/public/gnb/GNB.tsx
  src/components/public/gnb/components/ProfileComponent.tsx
  src/hooks/useWishList.tsx
  src/provider/CountProvider.tsx
Labels: feat, fix

#137 #136 로그인 페이지 테스트 코드 작성
  cypress/e2e/logIn.cy.ts
Labels: feat

#139 #138 sign up e2e test 완료
  cypress/e2e/signup.cy.ts
  src/actions/postSignupFn.ts
Labels: feat

#142 #141 card 컴포넌트 수정
  src/components/pages/mypage/MyPageDefault.tsx
  src/components/pages/mypage/MyPageInfoWrapper.tsx
Labels: feat

#146 feat : resize될때마다 padding 변경
  src/components/pages/findMeeting/MeetingCard/MeetingDetail/BottomBanner.tsx
  src/components/pages/findMeeting/MeetingCard/MeetingDetail/MeetingDetail.tsx
Labels: refactoring, feat

#150 #149 auth 디테일 수정 및 jest, cypress lint 충돌 문제 해결
  .eslintrc.json
  cypress/tsconfig.json
  jest.config.js
  src/app/auth/AuthLayout.tsx
  src/app/auth/layout.tsx
  src/components/pages/auth/@signin/SigninForm.tsx
  src/components/pages/auth/@signup/SignupForm.tsx
  tsconfig.json
Labels: fix

#151 148 찜한 모임 페이지 e2e 테스트 진행
  .eslintrc.json
  cypress/e2e/signup.cy.ts
  cypress/e2e/wishlist.cy.ts
Labels: feat

#152 fix : 모임 찾기 버그 수정
  package-lock.json
  package.json
  src/app/findMeeting/page.tsx
  src/components/pages/findMeeting/CreateMeeting/CreateMeetingForm.tsx
  src/components/pages/findMeeting/CreateMeeting/selectComponents/SelectServiceButton.tsx
  src/components/pages/findMeeting/CreateMeeting/selectComponents/SelectTimeButton.tsx
  src/components/pages/findMeeting/MeetingCard/MeetingDetail/BottomBanner.tsx
Labels: refactoring, feat, fix

#154 chore: yaml 파일 추가
  .github/workflows/dispatch.yaml
  .github/workflows/trigger-dispatch.yaml
Labels: CI 및 라이브러리 관련 설정

#155 yaml 파일 추가
  .github/workflows/dispatch.yaml
  .github/workflows/trigger-dispatch.yaml
Labels: CI 및 라이브러리 관련 설정

#156 yaml 작동 test
  README.md
Labels: CI 및 라이브러리 관련 설정

#157 yaml 동작 테스트
  README.md
Labels: CI 및 라이브러리 관련 설정

#163 #162 리뷰 생성 및 별점 버그 수정
  src/components/pages/allReview/Scores/Scores.tsx
  src/components/public/modal/ReviewModal.tsx
  src/hooks/Review/useScoreCalculation.tsx
Labels: fix

#159 #158 cypress 환경변수 설정 및 적용
  cypress.config.ts
  cypress/e2e/logIn.cy.ts
  cypress/e2e/wishlist.cy.ts
Labels: fix

#161 #160 회원가입 e2e 테스트 로직 변경
  .eslintrc.json
  cypress.config.ts
  cypress/e2e/signup.cy.ts
  cypress/e2e/wishlist.cy.ts
  src/hooks/usePostSignup.ts
Labels: fix

#167 166 마이페이지 레이아웃 변경
  src/actions/Auths/checkLogin.ts
  src/actions/Auths/editProfileInfo.ts
  src/actions/Auths/getUserDataFn.ts
  src/actions/Auths/getUserInfo.ts
  src/actions/Auths/onLogout.ts
  src/actions/Auths/postSigninFn.ts
  src/actions/Auths/postSignupFn.ts
  src/actions/Auths/setCookies.ts
  src/actions/Gatherings/cancelMeeting.ts
  src/actions/Gatherings/fetchMyPageInfo.ts
  src/actions/Gatherings/generateGathering.ts
  src/actions/Gatherings/getAllReviews.ts
  src/actions/Gatherings/getMeetingDetail.ts
  src/actions/Gatherings/getMeetingList.ts
  src/actions/Gatherings/getParticipants.ts
  src/actions/Gatherings/joinGathering.ts
  src/actions/Gatherings/quitMeeting.ts
  src/actions/Reviews/addReview.ts
  src/actions/Reviews/allReviewActions.ts
  src/actions/Reviews/getScoreReview.ts
  src/app/(MyPage)/mypage/@addReview/(.)addReview/page.tsx
  src/app/(MyPage)/mypage/@addReview/default.tsx
  src/app/(MyPage)/mypage/@edit/(.)edit/page.tsx
  src/app/(MyPage)/mypage/@edit/default.tsx
  src/app/(MyPage)/mypage/layout.tsx
  src/app/(MyPage)/mypage/page.tsx
  src/app/findMeeting/page.tsx
  src/app/not-found.tsx
  src/components/pages/allReview/Scores/Scores.tsx
  src/components/pages/findMeeting/MeetingCard/MeetingDetail/BottomBanner.tsx
  src/components/pages/findMeeting/MeetingCard/MeetingDetail/MeetingDetail.tsx
  src/components/pages/findMeeting/MeetingCard/MeetingList/MeetingList.tsx
  src/components/pages/mainpage/ReviewPreview.test.tsx
  src/components/pages/mainpage/ReviewPreview.tsx
  src/components/pages/mypage/CancelButton.tsx
  src/components/pages/mypage/MyPageInfoTap.tsx
  src/components/pages/mypage/MyPageInfoTapButton.tsx
  src/components/pages/mypage/MyPageInfoWrapper.tsx
  src/components/pages/mypage/ReviewStateButton.tsx
  src/components/public/Card/Atom/CardBtn.tsx
  src/components/public/Card/Card.tsx
  src/components/public/LogoutBtn.tsx
  src/components/public/ProfileBox.tsx
  src/components/public/gnb/components/ProfileComponent.tsx
  src/components/public/modal/CancelModal.tsx
  src/components/public/modal/ProfileEditModal.tsx
  src/components/public/modal/ReviewModal.tsx
  src/hooks/Gatherings/useCreateGathering.tsx
  src/hooks/Gatherings/useJoinGathering.tsx
  src/hooks/Review/useAllReview.tsx
  src/hooks/Review/useScoreCalculation.tsx
  src/hooks/useGetMeetingList.tsx
  src/hooks/useGetUserData.ts
  src/hooks/useMeetingDetail.tsx
  src/hooks/usePostSignin.tsx
  src/hooks/usePostSignup.ts
  tailwind.config.ts
Labels: feat, style

#170 #169 모달 버그 수정
  src/app/(MyPage)/mypage/layout.tsx
  src/components/public/modal/ProfileEditModal.tsx
  src/components/public/modal/ReviewModal.tsx
Labels: fix, style

#172 #171 metadata 수정
  src/app/(MyPage)/mypage/layout.tsx
Labels: hotfix

#173 test : 모든 리뷰 e2e 테스트
  cypress/e2e/allReview.cy.ts
  src/app/allReview/page.tsx
  src/components/pages/allReview/List.tsx
  src/components/pages/allReview/Scores/Atoms/RatingBar.tsx
  src/components/pages/allReview/Scores/Scores.tsx
Labels: refactoring, style

#175 #165 마이페이지 e2e 테스트
  cypress/e2e/mypage.cy.ts
  cypress/support/commands.ts
  package-lock.json
  package.json
Labels: feat

#176 feat : 모임 찾기, 상세, 찜한 모임 UI 수정
  src/app/findMeeting/page.tsx
  src/app/wishlist/page.tsx
  src/components/pages/findMeeting/MeetingCard/Atoms/ParticipantGage.tsx
  src/components/pages/findMeeting/MeetingCard/MeetingDetail/BottomBanner.tsx
  src/components/pages/findMeeting/MeetingCard/MeetingDetail/MeetingDetail.tsx
  src/components/pages/findMeeting/MeetingCard/MeetingList/MeetingList.tsx
  src/components/pages/wishlist/List.tsx
Labels: refactoring, feat, style

#179 #177 mypage 관련 타입 분리 및 정리
  src/actions/Auths/getUserInfo.ts
  src/actions/Gatherings/fetchMyPageInfo.ts
  src/app/(MyPage)/mypage/@addReview/(.)addReview/page.tsx
  src/app/(MyPage)/mypage/@edit/(.)edit/page.tsx
  src/app/(MyPage)/mypage/layout.tsx
  src/components/pages/mypage/MyPageInfoTap.tsx
  src/components/pages/mypage/MyPageInfoTapButton.tsx
  src/components/pages/mypage/MyPageInfoWrapper.tsx
  src/components/pages/mypage/ReviewStateButton.tsx
  src/components/public/img/Profile.tsx
  src/components/public/modal/ProfileEditModal.tsx
  src/components/public/modal/ReviewModal.tsx
  src/types/mypage/mypage.d.ts
Labels: refactoring

#181 #178 refactor gnb 디자인 및 디테일 에러 수정
  public/icon/staticIcon/menuIcon.svg
  src/app/layout.tsx
  src/components/pages/auth/@signin/SigninForm.tsx
  src/components/public/gnb/GNB.tsx
  src/components/public/gnb/components/AnimatedMenu.tsx
  src/components/public/gnb/components/AnimatedMenuIcon.tsx
  src/components/public/gnb/components/ProfileComponent.tsx
  src/components/public/icon/staticIcon/MenuIcon.tsx
Labels: refactoring, style

#184 #183 모임찾기 페이지 관련 타입 분리 및 정리
  src/actions/Gatherings/getMeetingList.ts
  src/app/findMeeting/[slug]/page.tsx
  src/app/findMeeting/page.tsx
  src/components/pages/findMeeting/CreateMeeting/CreateMeetingForm.tsx
  src/components/pages/findMeeting/CreateMeeting/selectComponents/SelectServiceButton.tsx
  src/components/pages/findMeeting/CreateMeeting/selectComponents/SelectServiceRadioGroup.tsx
  src/components/pages/findMeeting/CreateMeeting/selectComponents/SelectTimeButton.tsx
  src/components/pages/findMeeting/FilterCalendar/FilterCalendar.tsx
  src/components/pages/findMeeting/FilterSort/FilterSort.tsx
  src/components/pages/findMeeting/FilterTab/FilterTab.tsx
  src/components/pages/findMeeting/MeetingCard/MeetingDetail/BottomBanner.tsx
  src/components/pages/findMeeting/MeetingCard/MeetingDetail/MeetingDetail.tsx
  src/components/pages/findMeeting/MeetingCard/MeetingList/MeetingList.tsx
  src/components/pages/wishlist/List.tsx
  src/components/pages/wishlist/WishBtn.tsx
  src/components/public/Card/Card.tsx
  src/components/public/Card/MyCard/MyCard.tsx
  src/components/public/Filter/Filter.tsx
  src/components/public/modal/CompleteSignUpModal.tsx
  src/hooks/useGetMeetingList.tsx
  src/hooks/useWishList.tsx
  src/types/card/props.ts
  src/types/findMeeting/findMeeting.d.ts
  src/types/meeting/meeting.ts
  src/types/wishlist/wishlist.ts
Labels: refactoring

#186 #185 auth 페이지의 서버 컴포넌트로의 변경 및 에러 페이지 오류 수정
  src/app/auth/@signin/page.tsx
  src/app/auth/@signup/page.tsx
  src/app/auth/default.tsx
  src/app/auth/layout.tsx
  src/app/auth/page.tsx
  src/components/pages/auth/AuthArticle.tsx
  src/components/public/gnb/GNB.tsx
Labels: refactoring, fix

#188 #187 폼 제출 시 유효성 검증 로직 추가
  src/components/public/modal/ProfileEditModal.tsx
Labels: hotfix

#189 style : 메인 페이지 구성
  package-lock.json
  package.json
  public/img/banner/banner01.png
  public/img/banner/banner02.png
  public/img/banner/banner03.png
  public/img/logo_large.svg
  src/app/allReview/page.tsx
  src/app/font/TmoneyRoundWind/TmoneyRoundWind-ExtraBold.woff
  src/app/font/TmoneyRoundWind/TmoneyRoundWind-ExtraBold.woff2
  src/app/globals.css
  src/app/layout.tsx
  src/app/not-found.tsx
  src/app/page.tsx
  src/components/pages/findMeeting/MeetingCard/Atoms/DateTag.tsx
  src/components/pages/mainpage/Banner.tsx
  src/components/pages/mainpage/MainReview.tsx
  src/components/pages/mainpage/NewMeeting.tsx
  src/components/public/Skeleton/MainCardSkeleton.tsx
  src/components/public/Skeleton/MainReviewSkeleton.tsx
  src/components/public/gnb/GNB.tsx
  src/components/public/gnb/components/AnimatedMenu.tsx
  src/components/public/gnb/components/AnimatedMenuIcon.tsx
  src/components/public/gnb/components/ProfileComponent.tsx
  src/types/review/filter.d.ts
  src/types/wishlist/wishlist.d.ts
  tailwind.config.ts
Labels: feat, style

#194 #193 모임생성 및 삭제 관련 마이페이지 반영 불가 버그
  src/app/(MyPage)/mypage/page.tsx
  src/components/pages/findMeeting/CreateMeeting/CreateMeetingForm.tsx
  src/components/pages/mypage/MyPageInfoWrapper.tsx
  src/components/public/Card/Card.tsx
Labels: hotfix

#195 191 모달 창 에니메이션 추가
  src/components/public/modal/ProfileEditModal.tsx
  src/components/public/modal/ReviewModal.tsx
Labels: feat

#199 fix : 유저 피드백에 의한 기능 추가
  src/app/(MyPage)/mypage/layout.tsx
  src/app/(MyPage)/mypage/page.tsx
  src/app/allReview/page.tsx
  src/app/favicon.ico
  src/app/findMeeting/page.tsx
  src/app/page.tsx
  src/app/wishlist/page.tsx
  src/app/wishlist/wishlist.test.tsx
  src/components/pages/allReview/FilterSort.tsx
  src/components/pages/allReview/List.tsx
  src/components/pages/allReview/Scores/Scores.tsx
  src/components/pages/findMeeting/CreateMeeting/CreateMeetingForm.tsx
  src/components/pages/findMeeting/MeetingCard/Atoms/DateTag.tsx
  src/components/pages/findMeeting/MeetingCard/MeetingDetail/BottomBanner.tsx
  src/components/pages/findMeeting/MeetingCard/MeetingDetail/MeetingDetail.tsx
  src/components/pages/findMeeting/MeetingCard/MeetingList/MeetingList.tsx
  src/components/pages/mainpage/MainReview.tsx
  src/components/pages/mainpage/NewMeeting.tsx
  src/components/pages/wishlist/List.tsx
  src/components/pages/wishlist/WishBtn.tsx
  src/components/public/ResetFilter.tsx
  src/components/public/gnb/GNB.tsx
  src/components/public/gnb/components/AnimatedMenu.tsx
  src/hooks/useGetMeetingList.tsx
Labels: feat, fix

#202 #182 로그인회원가입 페이지 관련 타입 분리 및 리팩토링
  src/actions/Auths/postSigninFn.ts
  src/actions/Auths/postSignupFn.ts
  src/actions/Gatherings/generateGathering.ts
  src/actions/Reviews/addReview.ts
  src/actions/Reviews/getAllReviews.ts
  src/app/auth/page.tsx
  src/components/pages/auth/@signin/SigninForm.tsx
  src/components/pages/auth/@signup/SignupForm.tsx
  src/components/pages/auth/AuthArticle.tsx
  src/components/pages/mainpage/ReviewPreview.test.tsx
  src/components/pages/mainpage/ReviewPreview.tsx
  src/components/public/button/Button.tsx
  src/hooks/Gatherings/useCreateGathering.tsx
  src/types/auth/auth.d.ts
  src/types/findMeeting/findMeeting.d.ts
  src/types/mypage/mypage.d.ts
Labels: refactoring

#201 refactor : 리뷰 페이지, 찜 목록 페이지 타입 정리
  src/actions/Reviews/allReviewActions.ts
  src/actions/Reviews/getAllReviews.ts
  src/actions/Reviews/getScoreReview.ts
  src/app/allReview/page.tsx
  src/components/pages/allReview/FilterSort.tsx
  src/components/pages/allReview/List.tsx
  src/components/pages/allReview/Scores/Atoms/RatingBar.tsx
  src/components/pages/allReview/Scores/Scores.tsx
  src/components/pages/findMeeting/MeetingCard/MeetingDetail/MeetingDetail.tsx
  src/components/pages/wishlist/ByeBtn.tsx
  src/components/pages/wishlist/List.tsx
  src/components/public/ResetFilter.tsx
  src/components/public/Review/Review.tsx
  src/hooks/Review/useAllReview.tsx
  src/hooks/Review/useScoreCalculation.tsx
  src/types/findMeeting/findMeeting.d.ts
  src/types/review/filter.d.ts
  src/types/review/review.d.ts
  src/types/wishlist/wishlist.d.ts
Labels: refactoring

#204 #203 모임 상세 페이지에서 api 오류가 발생했을 때 처리하는 로직을 추가하고 리팩토링함
  src/components/pages/findMeeting/MeetingCard/MeetingDetail/BottomBanner.tsx
  src/components/pages/findMeeting/MeetingCard/MeetingDetail/MeetingDetail.tsx
  src/components/pages/findMeeting/MeetingCard/MeetingDetail/components/MeetingImage.tsx
  src/components/pages/findMeeting/MeetingCard/MeetingDetail/components/MeetingInformationCard.tsx
  src/components/pages/findMeeting/MeetingCard/MeetingDetail/components/MeetingReviewList.tsx
  src/components/public/bottomFloatingBar/BottomFloatingBar.test.tsx
  src/components/public/bottomFloatingBar/BottomFloatingBar.tsx
  src/hooks/useGetMeetingDetailData.ts
Labels: refactoring, fix

#206 #205 mypage 타입 정리
  src/actions/Reviews/addReview.ts
  src/components/public/modal/ReviewModal.tsx
  src/types/mypage/mypage.d.ts
Labels: refactoring

#208 #207 mypage 코드 관련 파일 분리
  src/app/(MyPage)/mypage/page.tsx
  src/components/pages/mypage/MyPageInfoTap.tsx
  src/hooks/mypage/myPageQuery.ts
  src/hooks/mypage/useTapHook.ts
Labels: refactoring

#209 feat : UI 디테일
  package-lock.json
  package.json
  src/app/page.tsx
  src/components/pages/findMeeting/MeetingCard/MeetingList/MeetingList.tsx
  src/components/pages/mainpage/MainReview.tsx
  src/components/pages/mainpage/NewMeeting.tsx
  src/components/public/Toast.tsx
  src/components/public/bottomFloatingBar/BottomFloatingBar.tsx
  src/components/public/gnb/components/SideBarMenu.tsx
Labels: feat, fix

#212 #211 ui 및 refactoring 에 따른 test code 수정
  cypress/e2e/allReview.cy.ts
  cypress/e2e/gnb.cy.ts
  cypress/e2e/home.cy.ts
  cypress/e2e/mypage.cy.ts
  cypress/e2e/signup.cy.ts
  cypress/e2e/wishlist.cy.ts
Labels: fix

#215 refactor : 함수형으로 리팩토링
  package-lock.json
  src/components/pages/allReview/Scores/Scores.tsx
  src/hooks/Review/useScoreCalculation.tsx
  src/types/review/review.d.ts
Labels: refactoring

#216 #211 gnb 수정에 따른 test 코드 수정
  cypress/e2e/gnb.cy.ts
Labels: fix

#218 hotfix: 기본 상수 수정
  src/app/page.tsx
  src/constants/limit.ts
Labels: hotfix
