Repository sprint-team5/dallaem, pull requests merged in 2024-07, with the labels that each got.

#5 4 pr merge할 때 jest 테스트 코드 통과 여부 확인하게 하기
  .github/workflows/test.yaml
  package-lock.json
  package.json
  tsconfig.json
Labels: CI 및 라이브러리 관련 설정

#9 eslint 오류 수정 및 기타 기능 추가
  .eslintrc.json
  .github/workflows/test.yaml
  package-lock.json
  package.json
  src/types/common/global.d.ts
Labels: CI 및 라이브러리 관련 설정

#11 10 tanstack query 설치 및 초기 세팅
  .eslintignore
  .eslintrc.json
  .gitignore
  __test__/page.test.jsx
  package-lock.json
  package.json
  public/next.svg
  public/vercel.svg
  src/app/globals.css
  src/app/layout.tsx
  src/app/page.tsx
  src/components/app/provider.tsx
  tsconfig.json
Labels: CI 및 라이브러리 관련 설정

#22 chore: 기본 폰트 추가 및 적용
  src/app/font/Pretendard-Bold.subset.woff2
  src/app/font/Pretendard-Light.subset.woff2
  src/app/font/Pretendard-Medium.subset.woff2
  src/app/font/Pretendard-Regular.subset.woff2
  src/app/font/Pretendard-SemiBold.subset.woff2
  src/app/font/Pretendard-Thin.subset.woff2
  src/app/layout.tsx
Labels: CI 및 라이브러리 관련 설정

#25 24 jest가 svg 처리할 수 있게 추가함
  .eslintrc.json
  __mocks__/svgrMock.js
  jest.config.js
  package-lock.json
  package.json
  src/types/common/global.d.ts
  tsconfig.json
Labels: CI 및 라이브러리 관련 설정

#28 #13 공용 모달 컴포넌트 생성
  public/img/profile/defaultProfile.jpg
  public/img/profile/editBtn.jpg
  public/img/profile/profileHeader-lg.jpg
  public/img/profile/profileHeader-md.jpg
  public/img/profile/profileHeader-sm.jpg
  src/app/(myPage)/mypage/page.tsx
  src/components/public/CloseBtn.tsx
  src/components/public/LogoutBtn.tsx
  src/components/public/ProfileBox.tsx
  src/components/public/ProfileEditBtn.tsx
  src/components/public/modal/CancelModal.tsx
  src/components/public/modal/CompleteSignUpModal.tsx
  src/components/public/modal/GenerateMeetUpModal.tsx
  src/components/public/modal/ProfileEditModal.tsx
  src/components/public/modal/ReviewModal.tsx
  src/lib/generateMeetUp.ts
  src/public/icon/closeIcon.svg
  tailwind.config.ts
  tsconfig.json
Labels: feat

#29 #14 카드 리뷰 캘린더 공용 컴포넌트 생성
  .eslintrc.json
  __test__/components/public/Calendars.test.jsx
  __test__/components/public/Card.test.jsx
  __test__/components/public/Review.test.jsx
  package-lock.json
  package.json
  public/img/profile/defaultProfile.png
  src/app/wishlist/page.tsx
  src/components/public/Calendars/Calendars.scss
  src/components/public/Calendars/Calendars.tsx
  src/components/public/Card.tsx
  src/components/public/Review.tsx
Labels: feat

#30 16 ic 컴포넌트 추가
  __mocks__/svgrMock.js
  __mocks__/svgrMock.jsx
  jest.config.js
  src/components/public/icon/dynamicIcon/Arrow.test.tsx
  src/components/public/icon/dynamicIcon/Arrow.tsx
  src/components/public/icon/dynamicIcon/Checkbox.test.tsx
  src/components/public/icon/dynamicIcon/Checkbox.tsx
  src/components/public/icon/dynamicIcon/Heart.test.tsx
  src/components/public/icon/dynamicIcon/Heart.tsx
  src/components/public/icon/dynamicIcon/Save.test.tsx
  src/components/public/icon/dynamicIcon/Save.tsx
  src/components/public/icon/dynamicIcon/Sort.test.tsx
  src/components/public/icon/dynamicIcon/Sort.tsx
  src/components/public/icon/staticIcon/Alarm.tsx
  src/components/public/icon/staticIcon/ArrowRight.tsx
  src/components/public/icon/staticIcon/Bye.tsx
  src/components/public/icon/staticIcon/Check.tsx
  src/components/public/icon/staticIcon/Dalaemfit.tsx
  src/components/public/icon/staticIcon/Edit.tsx
  src/components/public/icon/staticIcon/Person.tsx
  src/components/public/icon/staticIcon/StaticIcons.test.tsx
  src/components/public/icon/staticIcon/VisibilityOff.tsx
  src/components/public/icon/staticIcon/VisibilityOn.tsx
  src/components/public/icon/staticIcon/Workation.tsx
  src/components/public/icon/staticIcon/X.tsx
  src/public/icon/dynamicIcon/arrow.svg
  src/public/icon/dynamicIcon/checkbox.svg
  src/public/icon/dynamicIcon/heart.svg
  src/public/icon/dynamicIcon/save_size=large_state=active.svg
  src/public/icon/dynamicIcon/save_size=large_state=discard.svg
  src/public/icon/dynamicIcon/save_size=large_state=inactive.svg
  src/public/icon/dynamicIcon/save_size=small_state=discard.svg
  src/public/icon/dynamicIcon/sort.svg
  src/public/icon/staticIcon/X.svg
  src/public/icon/staticIcon/alarm.svg
  src/public/icon/staticIcon/arrow_right.svg
  src/public/icon/staticIcon/bye.svg
  src/public/icon/staticIcon/check.svg
  src/public/icon/staticIcon/dalaemfit.svg
  src/public/icon/staticIcon/edit.svg
  src/public/icon/staticIcon/person.svg
  src/public/icon/staticIcon/visibility_off.svg
  src/public/icon/staticIcon/visibility_on.svg
  src/public/icon/staticIcon/workation.svg
  src/types/common/global.d.ts
  tsconfig.json
Labels: CI 및 라이브러리 관련 설정, feat

#37 #36 MSW library 설치
  package-lock.json
  package.json
Labels: CI 및 라이브러리 관련 설정

#43 #42 icon, img 파일 불러오는 경로 수정
  src/components/public/icon/dynamicIcon/Checkbox.tsx
  src/components/public/icon/dynamicIcon/Heart.tsx
  src/components/public/icon/dynamicIcon/Save.tsx
  src/components/public/icon/dynamicIcon/Sort.tsx
  src/components/public/icon/staticIcon/Alarm.tsx
  src/components/public/icon/staticIcon/ArrowRight.tsx
  src/components/public/icon/staticIcon/Bye.tsx
  src/components/public/icon/staticIcon/Check.tsx
  src/components/public/icon/staticIcon/Dalaemfit.tsx
  src/components/public/icon/staticIcon/Edit.tsx
  src/components/public/icon/staticIcon/Person.tsx
  src/components/public/icon/staticIcon/VisibilityOff.tsx
  src/components/public/icon/staticIcon/VisibilityOn.tsx
  src/components/public/icon/staticIcon/Workation.tsx
  src/components/public/icon/staticIcon/X.tsx
  src/components/public/img/Edit.tsx
  src/components/public/img/Head.tsx
  src/components/public/img/ImgLogin.tsx
  src/components/public/img/Logo.tsx
  src/components/public/img/Profile.tsx
  src/components/public/img/ProfileBG.tsx
Labels: fix

#40 #38 button 컴포넌트 추가
  src/components/public/button/Button.test.tsx
  src/components/public/button/Button.tsx
Labels: feat

#53 #41 input, dropdown, textare 컴포넌트 추가
  .eslintrc.json
  public/icon/dynamicIcon/arrow.svg
  src/components/public/icon/staticIcon/VisibilityOff.tsx
  src/components/public/icon/staticIcon/VisibilityOn.tsx
  src/components/public/input/InputField.test.tsx
  src/components/public/input/InputField.tsx
  src/components/public/input/components/Dropdown.test.tsx
  src/components/public/input/components/Dropdown.tsx
  src/components/public/textarea/Textarea.test.tsx
  src/components/public/textarea/Textarea.tsx
  src/utill/useOutsideClick.ts
Labels: feat

#57 #51 모든 리뷰 페이지 레이아웃 구성
  jest.config.js
  jest.setup.js
  next.config.mjs
  package-lock.json
  package.json
  src/actions/allReviewActions.ts
  src/app/allReview/List.tsx
  src/app/allReview/allReview.test.tsx
  src/app/allReview/page.tsx
  src/components/public/Review/Review.tsx
  src/hooks/useAllReview.tsx
  src/lib/getGenerateMeetImage.ts
  tsconfig.json
Labels: feat

#58 #56 모임찾기 카드 컴포넌트,레이아웃 구현
  public/icon/staticIcon/clock.svg
  public/icon/staticIcon/confirmed.svg
  src/app/findMeeting/[slug]/page.tsx
  src/app/findMeeting/page.tsx
  src/components/pages/findMeeting/FilterCalendar/FilterCalendar.tsx
  src/components/pages/findMeeting/FilterSort/FilterSort.tsx
  src/components/pages/findMeeting/MeetingCard/Atoms/DateTag.tsx
  src/components/pages/findMeeting/MeetingCard/Atoms/ParticipantGage.tsx
  src/components/pages/findMeeting/MeetingCard/MeetingList/MeetingList.tsx
  src/components/public/Filter/Filter.tsx
  src/components/public/Spinner/Spinner.scss
  src/components/public/Spinner/Spinner.tsx
  src/lib/getMeetingList.ts
  src/types/meeting/meeting.ts
  src/utill/fetchParameterParser.ts
Labels: feat, fix

#64 #63 gnb layout shifting bug
  src/app/layout.tsx
  src/components/pages/layout/LootLayout.tsx
  src/components/public/gnb/GNB.tsx
  src/components/public/img/Profile.tsx
Labels: fix

#66 #65: name prop 추가
  src/components/public/input/InputField.test.tsx
  src/components/public/input/InputField.tsx
  src/components/public/input/components/Dropdown.tsx
Labels: feat, fix

#67 #33 마이페이지 기본 레이아웃 작업
  next.config.mjs
  public/img/profile_bg/profile-bg-lg.png
  public/img/profile_bg/profile-bg-md.png
  public/img/profile_bg/profile-bg-sm.png
  src/actions/allReviewActions.ts
  src/actions/apis/Auths.ts
  src/actions/apis/getMeetingList.ts
  src/actions/editProfileInfo.ts
  src/actions/generateMeetUp.ts
  src/actions/getScoreReview.ts
  src/actions/getUserInfo.ts
  src/actions/onLogout.ts
  src/app/(myPage)/mypage/@edit/(.)edit/page.tsx
  src/app/(myPage)/mypage/@edit/default.tsx
  src/app/(myPage)/mypage/layout.tsx
  src/app/(myPage)/mypage/page.tsx
  src/components/app/mypage/CancelButton.tsx
  src/components/public/CloseBtn.tsx
  src/components/public/LogoutBtn.tsx
  src/components/public/ProfileBox.tsx
  src/components/public/ProfileEditBtn.tsx
  src/components/public/gnb/components/ProfileComponent.tsx
  src/components/public/input/components/Dropdown.tsx
  src/components/public/modal/GenerateMeetUpModal.tsx
  src/components/public/modal/ProfileEditModal.tsx
  src/util/fetchParameterParser.ts
  src/util/useOutsideClick.ts
  tailwind.config.ts
Labels: feat

#71 #39 찜한 모임 페이지 레이아웃
  src/app/wishlist/List.tsx
  src/app/wishlist/page.tsx
  src/app/wishlist/wishlist.test.tsx
  src/components/pages/wishlist/ByeBtn.tsx
  src/components/pages/wishlist/List.tsx
  src/components/pages/wishlist/WishBtn.tsx
  src/hooks/useWishList.tsx
  src/types/wishlist/wishlist.ts
Labels: feat

#70 #58 모임상세 레이아웃
  src/actions/apis/getMeetingDetail.ts
  src/app/findMeeting/[slug]/page.tsx
  src/app/findMeeting/page.tsx
  src/components/pages/findMeeting/MeetingCard/Atoms/ParticipantGage.tsx
  src/components/pages/findMeeting/MeetingCard/MeetingDetail/MeetingDetail.tsx
  src/components/pages/findMeeting/MeetingCard/MeetingList/MeetingList.tsx
  src/constants/route.ts
  src/hooks/useMeetingDetail.tsx
Labels: feat, fix

#72 #69 마이 페이지 전체 정보 탭 생성
  src/actions/fetchMyPageInfo.ts
  src/app/(myPage)/mypage/page.tsx
  src/components/pages/mypage/CancelButton.tsx
  src/components/pages/mypage/MyPageInfoTap.tsx
  src/components/pages/mypage/MyPageInfoTapButton.tsx
  src/components/pages/mypage/MyPageInfoWrapper.tsx
  src/components/public/modal/ProfileEditModal.tsx
  src/components/public/modal/ReviewModal.tsx
Labels: feat
